name = "GeneralizedDubinsIntervalProblem"
uuid = "11014322-c36b-48e8-9f33-d4141ac63aad"
authors = ["Petr Vana <vanapet1@fel.cvut.cz>"]
version = "0.1.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
